  - title: "Identity Service Tests"
    description: "Keystone identity management and RBAC scenarios"
    workloads:
      - scenario:
          KeystoneBasic.add_and_remove_user_role: {}
        contexts:
          {{ user_context(tenants_amount, users_amount, use_existing_users) }}
        runner:
          {{ constant_runner(concurrency=min(50, 7*controllers_amount),times=min(200, 67*controllers_amount), is_smoke=smoke) }}
        sla:
          {{ no_failures_sla() }}

      - scenario:
          KeystoneBasic.create_add_and_list_user_roles: {}
        contexts:
          {{ user_context(tenants_amount, users_amount, use_existing_users) }}
        runner:
          {{ constant_runner(concurrency=min(50, 7*controllers_amount),times=min(200, 67*controllers_amount), is_smoke=smoke) }}
        sla:
          {{ no_failures_sla() }}

      - scenario:
          KeystoneBasic.create_and_list_tenants: {}
        contexts:
          {{ user_context(tenants_amount, users_amount, use_existing_users) }}
        runner:
          {{ constant_runner(concurrency=min(50, 2*controllers_amount),times=min(200, 10*controllers_amount), is_smoke=smoke) }}
        sla:
          {{ no_failures_sla() }}

      - scenario:
          KeystoneBasic.create_and_delete_role: {}
        contexts:
          {{ user_context(tenants_amount, users_amount, use_existing_users) }}
        runner:
          {{ constant_runner(concurrency=min(50, 7*controllers_amount),times=min(200, 67*controllers_amount), is_smoke=smoke) }}
        sla:
          {{ no_failures_sla() }}

      - scenario:
          KeystoneBasic.create_and_delete_service: {}
        contexts:
          {{ user_context(tenants_amount, users_amount, use_existing_users) }}
        runner:
          {{ constant_runner(concurrency=min(50, 7*controllers_amount),times=min(200, 67*controllers_amount), is_smoke=smoke) }}
        sla:
          {{ no_failures_sla() }}

      - scenario:
          KeystoneBasic.get_entities: {}
        contexts:
          {{ user_context(tenants_amount, users_amount, use_existing_users) }}
        runner:
          {{ constant_runner(concurrency=min(50, 3*controllers_amount),times=min(200, 67*controllers_amount), is_smoke=smoke) }}
        sla:
          {{ no_failures_sla() }}

      - scenario:
          KeystoneBasic.create_update_and_delete_tenant: {}
        contexts:
          {{ user_context(tenants_amount, users_amount, use_existing_users) }}
        runner:
          {{ constant_runner(concurrency=min(50, 7*controllers_amount),times=min(200, 67*controllers_amount), is_smoke=smoke) }}
        sla:
          {{ no_failures_sla() }}

