description: Test scenario for creating volume snapshots and listing them in Cinder
  block storage service.
subtasks:
- contexts:
    users:
      tenants: 1
      users_per_tenant: 1
    volumes:
      size: 1
  runner:
    constant:
      concurrency: 2
      times: 2
  scenario:
    CinderVolumes.create_and_list_snapshots:
      detailed: true
      force: false
  sla:
    failure_rate:
      max: 0
  title: Create And List Snapshots
title: Cinder Volume Snapshot Creation and Listing
version: 2
