description: Test scenario for creating volumes and cloning them in Cinder block storage
  service.
subtasks:
- contexts:
    users:
      tenants: 2
      users_per_tenant: 2
  runner:
    constant:
      concurrency: 2
      times: 3
  scenario:
    CinderVolumes.create_volume_and_clone:
      size: 1
  sla:
    failure_rate:
      max: 0
  title: Create Volume And Clone (variant 1)
- contexts:
    users:
      tenants: 2
      users_per_tenant: 2
  runner:
    constant:
      concurrency: 2
      times: 3
  scenario:
    CinderVolumes.create_volume_and_clone:
      nested_level: 3
      size:
        max: 5
        min: 1
  sla:
    failure_rate:
      max: 0
  title: Create Volume And Clone (variant 2)
title: Cinder Volume Creation and Cloning
version: 2
