---
version: 2
title: "Cinder Volume Type Creation and Deletion"
description: "Test scenario for creating and deleting volume types in Cinder block storage service."
subtasks:
  - title: "Create and delete volume type"
    scenario:
      CinderVolumeTypes.create_and_delete_volume_type:
        description: "rally tests creating types"
    runner:
      constant:
        times: 5
        concurrency: 2
    contexts:
      users:
        tenants: 2
        users_per_tenant: 2
    sla:
      failure_rate:
        max: 0
