description: Test scenario for creating volume backups in Cinder block storage service.
subtasks:
- contexts:
    roles:
    - member
    users:
      tenants: 1
      users_per_tenant: 1
  runner:
    constant:
      concurrency: 1
      times: 2
  scenario:
    CinderVolumes.create_volume_backup:
      create_backup_kwargs: {}
      create_volume_kwargs: {}
      do_delete: true
      size: 1
  sla:
    failure_rate:
      max: 0
  title: Create Volume Backup
title: Cinder Volume Backup Creation
version: 2
