{% set flavor_name = flavor_name or "m1.tiny" %}
---
version: 2
title: "Cinder Snapshot Creation and Volume Attachment"
description: "Test scenario for creating volume snapshots and attaching volumes in Cinder block storage service."
subtasks:
  - title: "Create snapshot and attach volume (lvmdriver-1)"
    scenario:
      CinderVolumes.create_snapshot_and_attach_volume:
        volume_type: "lvmdriver-1"
        size:
          min: 1
          max: 5
        image:
          name: "^cirros.*-disk$"
        flavor:
          name: "{{flavor_name}}"
    runner:
      constant:
        times: 4
        concurrency: 2
    contexts:
      users:
        tenants: 2
        users_per_tenant: 1
    sla:
      failure_rate:
        max: 0
  - title: "Create snapshot and attach volume (test type)"
    scenario:
      CinderVolumes.create_snapshot_and_attach_volume:
        volume_type: "test"
        size:
          min: 1
          max: 5
        image:
          name: "^cirros.*-disk$"
        flavor:
          name: "{{flavor_name}}"
    runner:
      constant:
        times: 4
        concurrency: 2
    contexts:
      users:
        tenants: 2
        users_per_tenant: 1
      volume_types:
        - "test"
    sla:
      failure_rate:
        max: 0
