description: Test scenario for creating volumes from snapshots in Cinder block storage
  service.
subtasks:
- contexts:
    users:
      tenants: 2
      users_per_tenant: 2
    volumes:
      size: 1
  runner:
    constant:
      concurrency: 2
      times: 3
  scenario:
    CinderVolumes.create_volume_from_snapshot:
      do_delete: true
  sla:
    failure_rate:
      max: 0
  title: Create Volume From Snapshot
title: Cinder Volume Creation from Snapshot
version: 2
