version: 2
title: "Cinder Volume Type Encryption Creation and Deletion"
description: "Test scenario for creating and deleting volume type encryption specifications in Cinder block storage service."
subtasks:
  - title: "Create and delete volume type encryption"
    scenario:
      CinderVolumeTypes.create_and_delete_encryption_type:
        provider: "LuksEncryptor"
        cipher: "aes-xts-plain64"
        key_size: 512
        control_location: "front-end"
    runner:
      constant:
        times: 4
        concurrency: 1
    contexts:
      users:
        tenants: 2
        users_per_tenant: 2
      volume_types: [
        "test_type1",
        "test_type2",
        "test_type3",
        "test_type4"
      ]
    sla:
      failure_rate:
        max: 0
