description: Test scenario for listing volume types in Cinder block storage service.
subtasks:
- contexts:
    users:
      tenants: 2
      users_per_tenant: 3
  runner:
    constant:
      concurrency: 2
      times: 10
  scenario:
    CinderVolumes.list_types:
      is_public: true
  sla:
    failure_rate:
      max: 0
  title: List Types
title: Cinder Volume Type Listing
version: 2
