---
version: 2
title: "Constant For Duration Runner"
description: "Demonstrates using constant runner with duration-based execution"
subtasks:
  - title: "Constant concurrency for duration"
    description: "Run with constant concurrency level for a specified duration"
    scenario:
      Dummy.dummy:
        sleep: 5
    runner:
      constant_for_duration:
        concurrency: 5
        duration: 30
