---
version: 2
title: Octavia Octavia Create And Show Loadbalancers
description: Test creating Octavia load balancer resources
subtasks:
- title: Create and show loadbalancers
  scenario:
    Octavia.create_and_show_loadbalancers: {}
  runner:
    constant:
      times: 5
      concurrency: 2
  contexts:
    users:
      tenants: 2
      users_per_tenant: 2
    roles:
    - load-balancer_member
    network: {}
  sla:
    failure_rate:
      max: 0
