---
version: 2
title: Glance Create And Get Image
description: Test creating Glance images
subtasks:
- title: Create and get image
  scenario:
    GlanceImages.create_and_get_image:
      image_location: http://download.cirros-cloud.net/0.5.2/cirros-0.5.2-x86_64-disk.img
      container_format: bare
      disk_format: qcow2
  runner:
    constant:
      times: 4
      concurrency: 2
  contexts:
    users:
      tenants: 2
      users_per_tenant: 2
  sla:
    failure_rate:
      max: 0
