---
version: 2
title: Dummy Allow Ssh
description: Test allow ssh operations
subtasks:
- title: Dummy allow ssh
  scenario:
    Dummy.openstack:
      sleep: 0.1
  runner:
    constant:
      times: 4
      concurrency: 2
  contexts:
    users:
      tenants: 1
      users_per_tenant: 2
    allow_ssh: null
