---
version: 2
title: Dummy Clusters
description: Test clusters operations
subtasks:
- title: Dummy Clusters (variant 1)
  scenario:
    Dummy.openstack:
      sleep: 0.1
  runner:
    constant:
      times: 1
      concurrency: 1
  contexts:
    users:
      tenants: 1
      users_per_tenant: 1
    cluster_templates:
      image_id: fedora-atomic-latest
      external_network_id: public
      dns_nameserver: 8.8.8.8
      flavor_id: m1.small
      docker_volume_size: 5
      network_driver: flannel
      coe: kubernetes
    clusters:
      node_count: 2
- title: Dummy Clusters (variant 2)
  scenario:
    Dummy.openstack:
      sleep: 0.1
  runner:
    constant:
      times: 1
      concurrency: 1
  contexts:
    users:
      tenants: 1
      users_per_tenant: 1
    cluster_templates:
      image_id: fedora-atomic-latest
      external_network_id: public
      dns_nameserver: 8.8.8.8
      flavor_id: m1.small
      docker_volume_size: 5
      network_driver: docker
      coe: swarm
    clusters:
      node_count: 2
- title: Dummy Clusters (variant 3)
  scenario:
    Dummy.openstack:
      sleep: 0.1
  runner:
    constant:
      times: 1
      concurrency: 1
  contexts:
    users:
      tenants: 1
      users_per_tenant: 1
    cluster_templates:
      image_id: ubuntu-mesos
      external_network_id: public
      dns_nameserver: 8.8.8.8
      flavor_id: m1.small
      network_driver: docker
      coe: mesos
    clusters:
      node_count: 2
