---
version: 2
title: "Task template with image command customizer context"
description: "This sample demonstrates the usage of image command customizer context for creating customized images with pre-installed commands."
subtasks:
  - title: "Test with image command customizer"
    workloads:
      - scenario:
          Dummy.openstack:
            sleep: 0.1
        runner:
          constant:
            concurrency: 1
            timeout: 3000
            times: 1
        contexts:
          image_command_customizer:
            command:
              local_path: "rally-jobs/extra/install_benchmark.sh"
              remote_path: "./install_benchmark.sh"
            flavor:
              name: m1.small
            image:
              name: "Fedora-x86_64-20-20140618-sda"
            userdata: "#cloud-config\ndisable_root: 0\nssh_pwauth: 1"
            username: root
          network: {}
          users:
            tenants: 1
            users_per_tenant: 1
