---
version: 2
title: "Task template with quotas context"
description: "This sample demonstrates the usage of quotas context for setting up resource quotas for different services."
subtasks:
  - title: "Test with Manila quotas"
    workloads:
      - scenario:
          Dummy.openstack:
            sleep: 0.1
        runner:
          constant:
            times: 4
            concurrency: 2
        contexts:
          users:
            tenants: 1
            users_per_tenant: 1
          quotas:
            manila:
              share_networks: -1
  - title: "Test with Cinder quotas"
    workloads:
      - scenario:
          Dummy.openstack:
            sleep: 0.1
        runner:
          constant:
            times: 4
            concurrency: 2
        contexts:
          users:
            tenants: 1
            users_per_tenant: 1
          quotas:
            cinder:
              volumes: -1
