---
version: 2
title: Volumes Context Configuration
description: Sample configuration for Rally volumes context showing volume creation setup
subtasks:
- title: Basic volumes context
  description: Create volumes for use in testing scenarios
  scenario:
    Dummy.openstack:
      sleep: 0.1
  runner:
    constant:
      times: 4
      concurrency: 2
  contexts:
    users:
      tenants: 1
      users_per_tenant: 2
    volumes:
      size: 1
      volumes_per_tenant: 4
