---
version: 2
title: Dummy Zones
description: Test zones operations
subtasks:
- title: Dummy zones
  scenario:
    Dummy.openstack:
      sleep: 0.1
  runner:
    constant:
      times: 4
      concurrency: 2
  contexts:
    users:
      tenants: 1
      users_per_tenant: 2
    zones:
      zones_per_tenant: 1
