---
version: 2
title: Keystone Create User Update Password
description: Test creating Keystone identity resources
subtasks:
- title: Create user update password
  scenario:
    KeystoneBasic.create_user_update_password: {}
  runner:
    constant:
      times: 100
      concurrency: 10
  sla:
    failure_rate:
      max: 0
