---
version: 2
title: Keystone Create And Get Role
description: Test creating Keystone identity resources
subtasks:
- title: Create and get role
  scenario:
    KeystoneBasic.create_and_get_role: {}
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 3
      users_per_tenant: 2
  sla:
    failure_rate:
      max: 0
