---
version: 2
title: Magnum Create Rcs
description: Test creating Magnum container resources
subtasks:
- title: Magnum Create Rcs (variant 1)
  scenario:
    K8sPods.create_rcs:
      manifests:
      - artifacts/rc_nginx.yaml.k8s
  runner:
    constant:
      times: 1
      concurrency: 1
  contexts:
    users:
      tenants: 1
      users_per_tenant: 1
    cluster_templates:
      image_id: fedora-atomic-latest
      external_network_id: public
      dns_nameserver: 8.8.8.8
      flavor_id: m1.small
      docker_volume_size: 5
      network_driver: flannel
      coe: kubernetes
    clusters:
      node_count: 2
    ca_certs:
      directory: /home/stack
  sla:
    failure_rate:
      max: 0
- title: Magnum Create Rcs (variant 2)
  scenario:
    K8sPods.create_rcs:
      manifests:
      - artifacts/rc_nginx.yaml.k8s
  runner:
    constant:
      times: 1
      concurrency: 1
  contexts:
    users:
      tenants: 1
      users_per_tenant: 1
    cluster_templates:
      image_id: fedora-atomic-latest
      external_network_id: public
      dns_nameserver: 8.8.8.8
      flavor_id: m1.small
      docker_volume_size: 5
      network_driver: flannel
      coe: kubernetes
      tls_disabled: true
    clusters:
      node_count: 2
  sla:
    failure_rate:
      max: 0
