---
version: 2
title: Heat stack creation and deletion
description: Test creating and deleting stacks in Heat orchestration service
subtasks:
- title: Create and delete stacks
  scenario:
    HeatStacks.create_and_delete_stack:
      template_path: samples/tasks/scenarios/heat/templates/default.yaml.template
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 2
      users_per_tenant: 3
  sla:
    failure_rate:
      max: 0
