---
version: 2
title: Heat Create Stack And Show Output Resource Group
description: Test creating Heat orchestration resources
subtasks:
- title: Heatstacks Create_Stack_And_Show_Output
  scenario:
    HeatStacks.create_stack_and_show_output:
      template_path: samples/tasks/scenarios/heat/templates/resource-group-with-outputs.yaml.template
      output_key: val1
  runner:
    constant:
      times: 5
      concurrency: 2
  contexts:
    users:
      tenants: 2
      users_per_tenant: 2
  sla:
    failure_rate:
      max: 0
- title: Heatstacks Create_Stack_And_Show_Output_Via_Api
  scenario:
    HeatStacks.create_stack_and_show_output_via_API:
      template_path: samples/tasks/scenarios/heat/templates/resource-group-with-outputs.yaml.template
      output_key: val1
  runner:
    constant:
      times: 5
      concurrency: 1
  contexts:
    users:
      tenants: 2
      users_per_tenant: 2
  sla:
    failure_rate:
      max: 0
