---
{%- set glance_image_location = glance_image_location|default("https://download.cirros-cloud.net/0.5.2/cirros-0.5.2-x86_64-disk.img") %}
{%- set image_name = image_name|default("^(cirros.*-disk|TestVM)$") %}
{%- set flavor_name = flavor_name|default("m1.tiny") %}
{%- set use_existing_users = use_existing_users|default(false) %}
{%- set service_list = service_list|default(["authentication", "cinder", "keystone", "nova", "glance", "neutron"]) %}
{%- set smoke = smoke|default(true) %}
{%- set controllers_amount = controllers_amount|default(1) %}
{%- if smoke %}
{%- set users_amount = 1 %}
{%- set tenants_amount = 1 %}
{%- else %}
{%- set users_amount = users_amount|default(1) %}
{%- set tenants_amount = tenants_amount|default(1) %}
{%- endif %}

{%- from "macro/macro.yaml" import user_context, vm_params, unlimited_volumes, constant_runner, rps_runner, no_failures_sla %}
{%- from "macro/macro.yaml" import volumes, unlimited_nova, unlimited_neutron, glance_args %}

version: 2
title: "OpenStack Certification Task"
description: "Comprehensive OpenStack platform validation and certification testing"

subtasks:

{% if "authentication" in service_list %}
{%- include "scenario/authentication.yaml"-%}
{% endif %}

{% if "cinder" in service_list %}
{%- include "scenario/cinder.yaml"-%}
{% endif %}

{% if "keystone" in service_list %}
{%- include "scenario/keystone.yaml"-%}
{% endif %}

{% if "nova" in service_list %}
{%- include "scenario/nova.yaml"-%}
{% endif %}

{% if "glance" in service_list %}
{%- include "scenario/glance.yaml"-%}
{% endif %}

{% if "neutron" in service_list %}
{%- include "scenario/neutron.yaml"-%}
{% endif %}
