---
version: 2
title: Barbican Create And List Secret
description: Test creating Barbican security resources
subtasks:
- title: Create and list secret
  scenario:
    BarbicanSecrets.create_and_list: {}
  runner:
    constant:
      times: 2
      concurrency: 1
  contexts:
    users:
      tenants: 1
      users_per_tenant: 1
  sla:
    failure_rate:
      max: 0
