---
version: 2
title: Barbican List Secrets
description: Test listing Barbican security resources
subtasks:
- title: List secrets
  scenario:
    BarbicanSecrets.list: {}
  runner:
    constant:
      times: 2
      concurrency: 1
  contexts:
    users:
      tenants: 1
      users_per_tenant: 1
  sla:
    failure_rate:
      max: 0
