{% set flavor_name = flavor_name or "m1.tiny" %}
{% set image_name = "^(cirros.*-disk|TestVM)$" %}
---
version: 2
title: Nova Boot Server Attach Volume And List Attachments
description: Test booting Nova servers
subtasks:
- title: Boot server attach volume and list attachments
  scenario:
    NovaServers.boot_server_attach_volume_and_list_attachments:
      flavor:
        name: '{{flavor_name}}'
      image:
        name: '{{image_name}}'
      volume_size: 1
      volume_num: 2
      boot_server_kwargs: {}
      create_volume_kwargs: {}
  runner:
    constant:
      times: 5
      concurrency: 2
  contexts:
    users:
      tenants: 2
      users_per_tenant: 2
  sla:
    failure_rate:
      max: 0
