{% set flavor_name = flavor_name or "m1.tiny" %}
---
version: 2
title: Nova Boot And Update Server
description: Test booting Nova servers
subtasks:
- title: Boot and update server
  scenario:
    NovaServers.boot_and_update_server:
      flavor:
        name: '{{flavor_name}}'
      image:
        name: ^cirros.*-disk$
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 3
      users_per_tenant: 2
  sla:
    failure_rate:
      max: 0
