{% set flavor_name = flavor_name or "m1.tiny" %}
---
version: 2
title: Nova Boot And List
description: Test booting Nova servers
subtasks:
- title: Boot and list
  scenario:
    NovaServers.boot_and_list_server:
      flavor:
        name: '{{flavor_name}}'
      image:
        name: ^cirros.*-disk$
      detailed: true
  runner:
    constant:
      times: 1
      concurrency: 1
  contexts:
    users:
      tenants: 1
      users_per_tenant: 1
  sla:
    failure_rate:
      max: 0
