{% set flavor_name = flavor_name or "m1.tiny" %}
---
version: 2
title: Nova Boot And Live Migrate
description: Test booting Nova servers
subtasks:
- title: Boot and live migrate
  scenario:
    NovaServers.boot_and_live_migrate_server:
      flavor:
        name: '{{flavor_name}}'
      image:
        name: ^cirros.*-disk$
      block_migration: false
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 1
      users_per_tenant: 1
  sla:
    failure_rate:
      max: 0
