{% set flavor_name = flavor_name or "m1.tiny" %}
---
version: 2
title: Nova Boot Lock Unlock And Delete
description: Test booting Nova servers
subtasks:
- title: Boot lock unlock and delete
  scenario:
    NovaServers.boot_lock_unlock_and_delete:
      flavor:
        name: '{{flavor_name}}'
      image:
        name: ^cirros.*-disk$
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 1
      users_per_tenant: 1
  sla:
    failure_rate:
      max: 0
