{% set flavor_name = flavor_name or "m1.tiny" %}
---
version: 2
title: Nova Boot From Volume And Resize
description: Test booting Nova servers
subtasks:
- title: Boot from volume and resize
  scenario:
    NovaServers.boot_server_from_volume_and_resize:
      flavor:
        name: '{{flavor_name}}'
      image:
        name: ^cirros.*-disk$
      to_flavor:
        name: m1.small
      confirm: true
      volume_size: 1
      force_delete: false
      do_delete: true
      boot_server_kwargs: {}
      create_volume_kwargs: {}
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 3
      users_per_tenant: 2
  sla:
    failure_rate:
      max: 0
