{% set flavor_name = flavor_name or "m1.tiny" %}
{% set volume_type = volume_type or "" %}
---
version: 2
title: Nova Boot From Volume Snapshot
description: Test booting Nova servers
subtasks:
- title: Boot from volume snapshot
  scenario:
    NovaServers.boot_server_from_volume_snapshot:
      flavor:
        name: '{{flavor_name}}'
      image:
        name: ^cirros.*-disk$
      volume_size: 10
      volume_type: '{{volume_type}}'
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 3
      users_per_tenant: 2
  sla:
    failure_rate:
      max: 0
