---
version: 2
title: Nova Create And Delete Keypair
description: Test deleting Nova servers
subtasks:
- title: Create and delete keypair
  scenario:
    NovaKeypair.create_and_delete_keypair: {}
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 3
      users_per_tenant: 2
  sla:
    failure_rate:
      max: 0
