---
version: 2
title: Nova Create Aggregate Add And Remove Host
description: Test creating Nova resources
subtasks:
- title: Create aggregate add and remove host
  scenario:
    NovaAggregates.create_aggregate_add_and_remove_host:
      availability_zone: nova
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 3
      users_per_tenant: 2
  sla:
    failure_rate:
      max: 0
