---
version: 2
title: Nova Create And List Aggregates
description: Test creating Nova resources
subtasks:
- title: Create and list aggregates
  scenario:
    NovaAggregates.create_and_list_aggregates:
      availability_zone: nova
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 3
      users_per_tenant: 2
  sla:
    failure_rate:
      max: 0
