---
version: 2
title: Nova Create And Get Aggregate Details
description: Test creating Nova resources
subtasks:
- title: Create and get aggregate details
  scenario:
    NovaAggregates.create_and_get_aggregate_details:
      availability_zone: nova
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 3
      users_per_tenant: 2
  sla:
    failure_rate:
      max: 0
