{% set flavor_name = flavor_name or "m1.tiny" %}
---
version: 2
title: Nova Resize Shutoff Server
description: Test server resize operations
subtasks:
- title: Resize shutoff server
  scenario:
    NovaServers.resize_shutoff_server:
      flavor:
        name: '{{flavor_name}}'
      image:
        name: ^cirros.*-disk$
      to_flavor:
        name: m1.small
      confirm: true
      force_delete: false
  runner:
    constant:
      times: 5
      concurrency: 2
  contexts:
    users:
      tenants: 2
      users_per_tenant: 2
  sla:
    failure_rate:
      max: 0
