---
version: 2
title: Neutron Create Policy Add And Remove Rules
description: Test creating Neutron networking resources
subtasks:
- title: Create policy add and remove rules
  scenario:
    NeutronFWaaS.create_policy_add_and_remove_rules: {}
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 1
      users_per_tenant: 1
  sla:
    failure_rate:
      max: 0
