---
version: 2
title: Neutron Create And Update Bgpvpns
description: Test creating Neutron networking resources
subtasks:
- title: Create and update bgpvpns
  scenario:
    NeutronBGPVPN.create_and_update_bgpvpns: {}
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 1
      users_per_tenant: 1
  sla:
    failure_rate:
      max: 0
