---
version: 2
title: Neutron Create And Update Subnets
description: Test creating Neutron networking resources
subtasks:
- title: Create and update subnets
  scenario:
    NeutronNetworks.create_and_update_subnets:
      subnet_cidr_start: 1.4.0.0/16
      subnets_per_network: 2
      subnet_update_args:
        enable_dhcp: false
  runner:
    constant:
      times: 10
      concurrency: 5
  contexts:
    network: {}
    users:
      tenants: 2
      users_per_tenant: 3
    quotas:
      neutron:
        network: -1
        subnet: -1
  sla:
    failure_rate:
      max: 0
