---
version: 2
title: Neutron Create And Show Subnets
description: Test creating Neutron networking resources
subtasks:
- title: Create and show subnets
  scenario:
    NeutronNetworks.create_and_show_subnets:
      network_create_args: {}
      subnet_create_args: {}
      subnet_cidr_start: 1.1.0.0/30
      subnets_per_network: 2
  runner:
    constant:
      times: 10
      concurrency: 5
  contexts:
    network: {}
    users:
      tenants: 2
      users_per_tenant: 3
    quotas:
      neutron:
        network: -1
        subnet: -1
  sla:
    failure_rate:
      max: 0
