---
version: 2
title: Neutron Create And Delete Ports
description: Test creating Neutron networking resources
subtasks:
- title: Create and delete ports
  scenario:
    NeutronNetworks.create_and_delete_ports:
      network_create_args: {}
      port_create_args: {}
      ports_per_network: 10
  runner:
    constant:
      times: 100
      concurrency: 10
  contexts:
    network: {}
    users:
      tenants: 3
      users_per_tenant: 3
    quotas:
      neutron:
        network: -1
        port: -1
  sla:
    failure_rate:
      max: 0
