---
version: 2
title: Neutron Create And List Security Groups
description: Test creating Neutron networking resources
subtasks:
- title: Create and list security groups
  scenario:
    NeutronSecurityGroup.create_and_list_security_groups:
      security_group_create_args: {}
  runner:
    constant:
      times: 100
      concurrency: 10
  contexts:
    users:
      tenants: 3
      users_per_tenant: 3
    quotas:
      neutron:
        security_group: -1
  sla:
    failure_rate:
      max: 0
