---
version: 2
title: Neutron Create And List Loadbalancers
description: Test creating Neutron networking resources
subtasks:
- title: Create and list loadbalancers
  scenario:
    NeutronLoadbalancerV2.create_and_list_loadbalancers:
      lb_create_args: {}
  runner:
    constant:
      times: 5
      concurrency: 2
  contexts:
    users:
      tenants: 2
      users_per_tenant: 2
    network: {}
  sla:
    failure_rate:
      max: 0
