---
version: 2
title: Neutron Create And Show Routers
description: Test creating Neutron networking resources
subtasks:
- title: Create and show routers
  scenario:
    NeutronNetworks.create_and_show_routers:
      subnet_cidr_start: 1.1.0.0/30
      subnets_per_network: 2
  runner:
    constant:
      times: 4
      concurrency: 2
  contexts:
    network: {}
    users:
      tenants: 2
      users_per_tenant: 2
    quotas:
      neutron:
        network: -1
        subnet: -1
        router: -1
  sla:
    failure_rate:
      max: 0
