{% set flavor_name = flavor_name or "m1.tiny" %}
---
version: 2
title: Neutron Create And Assoc Disassoc Routers Bgpvpns
description: Test creating Neutron networking resources
subtasks:
- title: Create and assoc disassoc routers bgpvpns
  scenario:
    NeutronBGPVPN.create_bgpvpn_assoc_disassoc_routers: {}
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 2
      users_per_tenant: 1
    network: {}
    servers:
      servers_per_tenant: 1
      auto_assign_nic: true
      flavor:
        name: '{{flavor_name}}'
      image:
        name: ^cirros.*-disk$
  sla:
    failure_rate:
      max: 0
