---
version: 2
title: Unknown Check Random Request
description: Test check random request operations
subtasks:
- title: Unknown check random request
  scenario:
    HttpRequests.check_random_request:
      requests:
      - url: http://www.example.com
        method: GET
        status_code: 200
      - url: http://www.openstack.org
        method: GET
      status_code: 200
  runner:
    constant:
      times: 20
      concurrency: 5
  sla:
    failure_rate:
      max: 0
