---
version: 2
title: Gnocchi List Archive Policy
description: Test listing Gnocchi metric resources
subtasks:
- title: List archive policy
  scenario:
    GnocchiArchivePolicy.list_archive_policy: {}
  runner:
    constant:
      times: 10
      concurrency: 2
  contexts:
    users:
      tenants: 2
      users_per_tenant: 3
  sla:
    failure_rate:
      max: 0
